# Generated by Django 4.0.2 on 2022-03-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Электронды пошта'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(max_length=255, verbose_name='Рөл'),
        ),
    ]
