# Generated by Django 4.0.2 on 2022-03-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_myuser_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
