# Generated by Django 4.0.2 on 2022-03-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creater_email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Курстың мұғалімі'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='main.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
