# Generated by Django 4.0.2 on 2022-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Аты-жөн'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Әкесінің аты'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='surname',
            field=models.CharField(default='', max_length=60, verbose_name='Фамилия'),
        ),
    ]
