# Generated by Django 4.0.2 on 2022-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_myuser_name_myuser_patronymic_myuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creater_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Курстың мұғалім аты'),
        ),
        migrations.AddField(
            model_name='course',
            name='creater_surname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Курстың мұғалім фамилиясы'),
        ),
    ]
