# Generated by Django 4.0.2 on 2022-03-11 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_creater_name_course_creater_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='Апта күні')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='Апта күні')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='Апта күні')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Студент')),
            ],
        ),
    ]
