# Generated by Django 4.0.2 on 2022-03-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_homework_student_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='name',
            field=models.CharField(default='Үй жұмысы', max_length=255, verbose_name='Үй жұмыс аты'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='Лекция', max_length=255, verbose_name='Лекцияның аты'),
        ),
        migrations.AddField(
            model_name='practice',
            name='name',
            field=models.CharField(default='Практика', max_length=255, verbose_name='Практиканың аты'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.homework', verbose_name='Үй жұмысы'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks', verbose_name='Файл'),
        ),
    ]
