# Generated by Django 4.0.2 on 2022-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_grade_homework_alter_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_level',
            field=models.IntegerField(default=1, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='student',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Топ'),
        ),
    ]
